[supabase]
SUPABASE_URL = "https://talfrnvdvmebgghxyoef.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhbGZybnZkdm1lYmdnaHh5b2VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDM1MjIsImV4cCI6MjA3Mzg3OTUyMn0.WYFflfbHb6Um4sWah0KMTWF92E-VtPI7NQyzly30Cbc"
[theme]
base="dark"